# Generated by Django 6.0.7 on 2026-07-31 06:13

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0017_godown_stockitem_stocktransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreGodown',
            fields=[
            ],
            options={
                'verbose_name': 'Godown',
                'verbose_name_plural': 'Godowns',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.godown',),
        ),
        migrations.CreateModel(
            name='StoreStockItem',
            fields=[
            ],
            options={
                'verbose_name': 'Stock Item',
                'verbose_name_plural': 'Stock Items',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.stockitem',),
        ),
        migrations.CreateModel(
            name='StoreStockTransaction',
            fields=[
            ],
            options={
                'verbose_name': 'Stock Transaction',
                'verbose_name_plural': 'Stock Transactions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.stocktransaction',),
        ),
    ]
