# Generated by Django 6.0.7 on 2026-07-31 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_stockcategory_alter_stockitem_category_and_more'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreStockCategory',
            fields=[
            ],
            options={
                'verbose_name': 'Stock Category',
                'verbose_name_plural': 'Stock Categories',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.stockcategory',),
        ),
        migrations.CreateModel(
            name='StoreStockSubCategory',
            fields=[
            ],
            options={
                'verbose_name': 'Stock Sub-Category',
                'verbose_name_plural': 'Stock Sub-Categories',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.stocksubcategory',),
        ),
    ]
