# Generated by Django 6.0.7 on 2026-07-31 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_seed_stock_categories'),
        ('store', '0002_storestockcategory_storestocksubcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialIssue',
            fields=[
            ],
            options={
                'verbose_name': 'Material Issue',
                'verbose_name_plural': 'Material Issue',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.stocktransaction',),
        ),
        migrations.CreateModel(
            name='PurchaseInward',
            fields=[
            ],
            options={
                'verbose_name': 'Purchase Inward',
                'verbose_name_plural': 'Purchase Inward',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.stocktransaction',),
        ),
    ]
