# Generated by Django 6.0.7 on 2026-07-31 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_purchaserequisitionitem_status'),
        ('store', '0003_materialissue_purchaseinward'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemsToIssue',
            fields=[
            ],
            options={
                'verbose_name': 'Item to Issue',
                'verbose_name_plural': 'Items to Issue',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.purchaserequisitionitem',),
        ),
    ]
