# Generated by Django 6.0.7 on 2026-08-01 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_stockitem_is_refillable_stockitem_is_returnable_and_more'),
        ('store', '0004_itemstoissue'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingReturnableItems',
            fields=[
            ],
            options={
                'verbose_name': 'Pending Returnable Item',
                'verbose_name_plural': 'Pending Returnable Items',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.stocktransaction',),
        ),
        migrations.CreateModel(
            name='RefillEntry',
            fields=[
            ],
            options={
                'verbose_name': 'Refill Entry',
                'verbose_name_plural': 'Refill Entries',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.refilllog',),
        ),
        migrations.CreateModel(
            name='StoreStockItemSerial',
            fields=[
            ],
            options={
                'verbose_name': 'Stock Item Serial',
                'verbose_name_plural': 'Stock Item Serials',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.stockitemserial',),
        ),
    ]
