# Generated by Django 6.0.7 on 2026-08-04 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_dashboard_preference'),
        ('store', '0005_pendingreturnableitems_refillentry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreStockItemPiece',
            fields=[
            ],
            options={
                'verbose_name': 'Stock Item Piece',
                'verbose_name_plural': 'Stock Item Pieces',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.stockitempiece',),
        ),
    ]
