# Generated by Django 6.0.1 on 2026-06-28 14:14

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Legal registered name of the business', max_length=255)),
                ('brand_name', models.CharField(blank=True, help_text='Trading name or brand name (if different from legal name)', max_length=255, null=True)),
                ('logo', models.ImageField(blank=True, help_text='Company logo (recommended: 200×200 px)', null=True, upload_to='company_logos/')),
                ('business_type', models.CharField(choices=[('proprietorship', 'Proprietorship'), ('partnership', 'Partnership'), ('llp', 'Limited Liability Partnership'), ('pvt_ltd', 'Private Limited'), ('public_ltd', 'Public Limited'), ('opc', 'One Person Company'), ('trust', 'Trust / Society'), ('other', 'Other')], default='proprietorship', help_text='Legal structure of the business', max_length=20)),
                ('industry_type', models.CharField(choices=[('hvac', 'HVAC & Air Conditioning'), ('refrigeration', 'Refrigeration'), ('electrical', 'Electrical'), ('plumbing', 'Plumbing'), ('fire_safety', 'Fire Safety'), ('elevator', 'Elevator & Escalator'), ('solar', 'Solar & Renewable Energy'), ('it_services', 'IT Services'), ('manufacturing', 'Manufacturing'), ('construction', 'Construction'), ('other', 'Other')], default='hvac', help_text='Primary industry / service domain', max_length=20)),
                ('website', models.URLField(blank=True, null=True)),
                ('gstin', models.CharField(blank=True, help_text='15-digit GST Identification Number (e.g., 27AABCU9603R1ZM)', max_length=15, null=True, verbose_name='GSTIN')),
                ('pan', models.CharField(blank=True, help_text='10-character Permanent Account Number (e.g., AABCU9603R)', max_length=10, null=True, verbose_name='PAN')),
                ('cin', models.CharField(blank=True, help_text='21-character Corporate Identification Number', max_length=21, null=True, verbose_name='CIN')),
                ('tan', models.CharField(blank=True, help_text='Tax Deduction and Collection Account Number', max_length=10, null=True, verbose_name='TAN')),
                ('msme_number', models.CharField(blank=True, help_text='Udyam Registration Number (e.g., UDYAM-XX-00-0000000)', max_length=20, null=True, verbose_name='MSME / Udyam Number')),
                ('gst_state_code', models.CharField(blank=True, choices=[('01', '01 - Jammu & Kashmir'), ('02', '02 - Himachal Pradesh'), ('03', '03 - Punjab'), ('04', '04 - Chandigarh'), ('05', '05 - Uttarakhand'), ('06', '06 - Haryana'), ('07', '07 - Delhi'), ('08', '08 - Rajasthan'), ('09', '09 - Uttar Pradesh'), ('10', '10 - Bihar'), ('11', '11 - Sikkim'), ('12', '12 - Arunachal Pradesh'), ('13', '13 - Nagaland'), ('14', '14 - Manipur'), ('15', '15 - Mizoram'), ('16', '16 - Tripura'), ('17', '17 - Meghalaya'), ('18', '18 - Assam'), ('19', '19 - West Bengal'), ('20', '20 - Jharkhand'), ('21', '21 - Odisha'), ('22', '22 - Chhattisgarh'), ('23', '23 - Madhya Pradesh'), ('24', '24 - Gujarat'), ('25', '25 - Daman & Diu'), ('26', '26 - Dadra & Nagar Haveli'), ('27', '27 - Maharashtra'), ('28', '28 - Andhra Pradesh (Old)'), ('29', '29 - Karnataka'), ('30', '30 - Goa'), ('31', '31 - Lakshadweep'), ('32', '32 - Kerala'), ('33', '33 - Tamil Nadu'), ('34', '34 - Puducherry'), ('35', '35 - Andaman & Nicobar Islands'), ('36', '36 - Telangana'), ('37', '37 - Andhra Pradesh (New)'), ('38', '38 - Ladakh')], help_text='State code as per GST registration', max_length=2, null=True, verbose_name='GST State Code')),
                ('address_line_1', models.CharField(help_text='Building / Floor / Street', max_length=255)),
                ('address_line_2', models.CharField(blank=True, help_text='Area / Landmark', max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('01', '01 - Jammu & Kashmir'), ('02', '02 - Himachal Pradesh'), ('03', '03 - Punjab'), ('04', '04 - Chandigarh'), ('05', '05 - Uttarakhand'), ('06', '06 - Haryana'), ('07', '07 - Delhi'), ('08', '08 - Rajasthan'), ('09', '09 - Uttar Pradesh'), ('10', '10 - Bihar'), ('11', '11 - Sikkim'), ('12', '12 - Arunachal Pradesh'), ('13', '13 - Nagaland'), ('14', '14 - Manipur'), ('15', '15 - Mizoram'), ('16', '16 - Tripura'), ('17', '17 - Meghalaya'), ('18', '18 - Assam'), ('19', '19 - West Bengal'), ('20', '20 - Jharkhand'), ('21', '21 - Odisha'), ('22', '22 - Chhattisgarh'), ('23', '23 - Madhya Pradesh'), ('24', '24 - Gujarat'), ('25', '25 - Daman & Diu'), ('26', '26 - Dadra & Nagar Haveli'), ('27', '27 - Maharashtra'), ('28', '28 - Andhra Pradesh (Old)'), ('29', '29 - Karnataka'), ('30', '30 - Goa'), ('31', '31 - Lakshadweep'), ('32', '32 - Kerala'), ('33', '33 - Tamil Nadu'), ('34', '34 - Puducherry'), ('35', '35 - Andaman & Nicobar Islands'), ('36', '36 - Telangana'), ('37', '37 - Andhra Pradesh (New)'), ('38', '38 - Ladakh')], help_text='State / Union Territory', max_length=2)),
                ('pincode', models.CharField(help_text='6-digit PIN code', max_length=6)),
                ('contact_email', models.EmailField(help_text='Primary business email', max_length=254)),
                ('contact_phone', models.CharField(help_text='Primary phone with country code (e.g., +919876543210)', max_length=15)),
                ('alternate_phone', models.CharField(blank=True, help_text='Secondary / landline number', max_length=15, null=True)),
                ('bank_name', models.CharField(blank=True, help_text='Name of the bank', max_length=100, null=True)),
                ('bank_account_number', models.CharField(blank=True, help_text='Bank account number', max_length=20, null=True)),
                ('bank_ifsc', models.CharField(blank=True, help_text='11-character IFSC code (e.g., SBIN0001234)', max_length=11, null=True, verbose_name='IFSC Code')),
                ('bank_branch', models.CharField(blank=True, help_text='Branch name', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True, help_text="Disable to suspend this company's access")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('role', models.ForeignKey(blank=True, help_text='Dynamic Role Assignment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_users', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.company')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('gst_number', models.CharField(blank=True, max_length=50, null=True)),
                ('billing_address', models.TextField()),
                ('shipping_address', models.TextField(help_text='Primary installation site')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='core.company')),
                ('user', models.OneToOneField(limit_choices_to={'role__name': 'Customer'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(max_length=50, unique=True)),
                ('designation', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('date_of_joining', models.DateField()),
                ('years_of_experience', models.DecimalField(decimal_places=1, help_text='Total years of experience', max_digits=4)),
                ('specific_expertise', models.TextField(blank=True, help_text='Specific skills or product expertise')),
                ('education_qualification', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=20)),
                ('emergency_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('resigned', 'Resigned'), ('terminated', 'Terminated')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='core.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'HRMS - Employee Master',
                'verbose_name_plural': 'HRMS - Employee Master',
            },
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone/Telephone'), ('walkin', 'Walk-in'), ('website', 'Website'), ('other', 'Other')], default='phone', max_length=20)),
                ('name', models.CharField(help_text='Prospect Name', max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('requirement', models.TextField(help_text='Generic requirement description')),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('quoted', 'Quotation Sent'), ('won', 'Won'), ('lost', 'Lost')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, limit_choices_to={'user__role__name__in': ['Admin', 'Sales']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.employee')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('customer_profile', models.ForeignKey(blank=True, help_text='Link if existing customer', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customerprofile')),
            ],
            options={
                'verbose_name_plural': 'Inquiries',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
            options={
                'verbose_name_plural': 'Product Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('specifications', models.TextField(help_text='Technical details, tonnage, capacity')),
                ('product_specific_terms', models.TextField(blank=True, help_text='Terms specific to this product to appear on quotes.', null=True)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.productcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('admin_discount_percent', models.DecimalField(decimal_places=2, default=0.0, help_text='Overall discount % applied by Admin', max_digits=5)),
                ('terms_and_conditions', models.TextField(default='1. Validity: 30 Days.\n2. Payment: 100% Advance.\n3. Delivery: 2-3 Weeks.', help_text='Standard terms applied to this quotation.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent to Customer'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='draft', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.customerprofile')),
                ('inquiry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.inquiry')),
                ('prepared_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.employee')),
            ],
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, help_text='Auto-pulled from product base price if left blank', max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.quotation')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('resolution_notes', models.TextField(blank=True, help_text='Internal notes by engineer', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_engineer', models.ForeignKey(blank=True, limit_choices_to={'user__role__name': 'Engineer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.employee')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customerprofile')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.product')),
            ],
        ),
    ]
