# Generated by Django 6.0.1 on 2026-06-28 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="e.g. 'Blue Star 2024 AC Brochure'", max_length=255)),
                ('document_type', models.CharField(choices=[('brochure', 'Brochure / Catalogue'), ('manual', 'User Manual'), ('spec_sheet', 'Specification Sheet'), ('other', 'Other')], default='brochure', max_length=20)),
                ('file', models.FileField(upload_to='product_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, help_text='Link to an entire category (e.g. all RACs)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='core.productcategory')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('product', models.ForeignKey(blank=True, help_text='Link to a specific product', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='core.product')),
            ],
        ),
    ]
