# Generated by Django 6.0.1 on 2026-06-28 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_invoice_invoiceitem_invoiceseries_invoice_series_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceticket',
            name='ticket_type',
            field=models.CharField(choices=[('complaint', 'Complaint / Breakdown'), ('installation', 'New Installation'), ('pm', 'Preventive Maintenance (AMC)'), ('paid', 'Paid Service Call')], default='complaint', max_length=20),
        ),
        migrations.CreateModel(
            name='AMCContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('third_party_brand', models.CharField(blank=True, help_text='Fill if not NOA product', max_length=100)),
                ('third_party_model', models.CharField(blank=True, max_length=100)),
                ('serial_number', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('contract_type', models.CharField(choices=[('comprehensive', 'Comprehensive (Parts & Labor)'), ('non_comprehensive', 'Non-Comprehensive (Labor Only)')], default='comprehensive', max_length=30)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('renewed', 'Renewed')], default='active', max_length=20)),
                ('pm_visits_per_year', models.PositiveIntegerField(default=3, help_text='Number of preventive maintenance visits covered')),
                ('auto_generate_tickets', models.BooleanField(default=True, help_text='Automatically schedule PM tickets on save')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customerprofile')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.product')),
            ],
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='amc_contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='core.amccontract'),
        ),
    ]
