# Generated by Django 6.0.1 on 2026-06-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_serviceticket_ticket_type_amccontract_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='products',
            field=models.ManyToManyField(blank=True, help_text='Select one or more specific products the customer is inquiring about.', to='core.product'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='requirement',
            field=models.TextField(blank=True, help_text='Generic requirement description', null=True),
        ),
    ]
