# Generated by Django 6.0.1 on 2026-06-28 16:01

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_inquiry_products_alter_inquiry_requirement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='products',
        ),
        migrations.AddField(
            model_name='amccontract',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.productcategory'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.productcategory'),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.productcategory'),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.productcategory'),
        ),
        migrations.AlterField(
            model_name='amccontract',
            name='product',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='subcategory', chained_model_field='subcategory', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.product'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='product',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='subcategory', chained_model_field='subcategory', on_delete=django.db.models.deletion.PROTECT, to='core.product'),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='product',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='subcategory', chained_model_field='subcategory', on_delete=django.db.models.deletion.CASCADE, to='core.product'),
        ),
        migrations.AlterField(
            model_name='serviceticket',
            name='product',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='subcategory', chained_model_field='subcategory', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.product'),
        ),
        migrations.CreateModel(
            name='ProductSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='core.productcategory')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
            options={
                'verbose_name_plural': 'Product Sub-Categories',
            },
        ),
        migrations.CreateModel(
            name='InquiryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.productcategory')),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.inquiry')),
                ('product', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='subcategory', chained_model_field='subcategory', on_delete=django.db.models.deletion.CASCADE, to='core.product')),
                ('subcategory', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='category', chained_model_field='category', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.productsubcategory')),
            ],
        ),
        migrations.AddField(
            model_name='amccontract',
            name='subcategory',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='category', chained_model_field='category', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.productsubcategory'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='subcategory',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='category', chained_model_field='category', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.productsubcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='category', chained_model_field='category', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.productsubcategory'),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='subcategory',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='category', chained_model_field='category', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.productsubcategory'),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='subcategory',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='category', chained_model_field='category', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.productsubcategory'),
        ),
    ]
