# Generated by Django 6.0.1 on 2026-06-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_inquiry_products_amccontract_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='availability_status',
            field=models.CharField(choices=[('in_stock', 'In Stock'), ('out_of_stock', 'Out of Stock'), ('discontinued', 'Discontinued')], default='in_stock', help_text='Current stock availability', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='brochure_url',
            field=models.URLField(blank=True, help_text='PDF brochure or catalogue link', null=True, verbose_name='Brochure / Catalogue URL'),
        ),
        migrations.AddField(
            model_name='product',
            name='division',
            field=models.CharField(blank=True, choices=[('consumer', 'Consumer'), ('commercial', 'Commercial')], help_text='Business division (Consumer / Commercial)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='model_year',
            field=models.CharField(blank=True, help_text='Model / BEE label year (e.g. 2025, 2026)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='mrp',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum Retail Price in INR', max_digits=12, null=True, verbose_name='MRP'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_url',
            field=models.URLField(blank=True, help_text='Official product page link', null=True, verbose_name='Product Page URL'),
        ),
        migrations.AddField(
            model_name='product',
            name='series',
            field=models.CharField(blank=True, help_text='Product series (e.g. D SERIES, Q SMART WI-FI SERIES)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='base_price',
            field=models.DecimalField(decimal_places=2, help_text='Market Operating Price (MOP) in INR', max_digits=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='specifications',
            field=models.TextField(blank=True, help_text='Capacity / technical specs (e.g. 1.5 Ton 5 Star)', null=True),
        ),
    ]
