# Generated by Django 6.0.1 on 2026-06-28 16:58

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_product_availability_status_product_brochure_url_and_more'),
    ]

    operations = [
        migrations.RunSQL('DELETE FROM core_productdocument; DELETE FROM core_serviceticket; DELETE FROM core_amccontract; DELETE FROM core_invoiceitem; DELETE FROM core_quotationitem; DELETE FROM core_inquiryitem; DELETE FROM core_product; DELETE FROM core_productcategory; DELETE FROM core_productsubcategory;'),
        migrations.AlterField(
            model_name='amccontract',
            name='category',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='division', chained_model_field='division', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.productcategory'),
        ),
        migrations.AlterField(
            model_name='inquiryitem',
            name='category',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='division', chained_model_field='division', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.productcategory'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='category',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='division', chained_model_field='division', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.productcategory'),
        ),
        migrations.AlterField(
            model_name='productdocument',
            name='category',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='division', chained_model_field='division', help_text='Link to an entire category (e.g. all RACs)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='core.productcategory'),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='category',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='division', chained_model_field='division', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.productcategory'),
        ),
        migrations.AlterField(
            model_name='serviceticket',
            name='category',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='division', chained_model_field='division', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.productcategory'),
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
            options={
                'verbose_name_plural': 'Divisions',
            },
        ),
        migrations.AddField(
            model_name='amccontract',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.division'),
        ),
        migrations.AddField(
            model_name='inquiryitem',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.division'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.division'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.division'),
        ),
        migrations.AddField(
            model_name='productdocument',
            name='division',
            field=models.ForeignKey(blank=True, help_text='Link to a division', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.division'),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.division'),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.division'),
        ),
        migrations.AlterField(
            model_name='product',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.division'),
        ),
    ]
