# Generated by Django 6.0.1 on 2026-06-28 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_amccontract_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='division',
            options={'ordering': ['name'], 'verbose_name': 'Division', 'verbose_name_plural': 'Divisions'},
        ),
        migrations.AddField(
            model_name='product',
            name='model_number',
            field=models.CharField(blank=True, help_text='Manufacturer model number (e.g. CSTO-18ADYA)', max_length=100, null=True, verbose_name='Model Number'),
        ),
    ]
