# Generated by Django 6.0.1 on 2026-06-28 17:19

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_division_options_product_model_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdocument',
            name='subcategory',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='category', chained_model_field='category', help_text='Link to a sub-category', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.productsubcategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='division', chained_model_field='division', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.productcategory'),
        ),
        migrations.AlterField(
            model_name='productdocument',
            name='product',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='subcategory', chained_model_field='subcategory', help_text='Link to a specific product', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='core.product'),
        ),
    ]
