# Generated by Django 6.0.7 on 2026-07-27 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_productdocument_subcategory_alter_product_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(help_text="Customer's PO reference number", max_length=100)),
                ('po_date', models.DateField(help_text="Date on the customer's PO")),
                ('po_file', models.FileField(blank=True, help_text='Scanned copy of the PO document', null=True, upload_to='purchase_orders/')),
                ('payment_terms', models.TextField(help_text="Payment terms as specified in the PO, e.g. '50% advance, 50% before dispatch'")),
                ('po_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Total PO value (defaults to quotation total if left blank)', max_digits=12, null=True)),
                ('status', models.CharField(choices=[('received', 'Received'), ('confirmed', 'Confirmed'), ('invoiced', 'Invoiced'), ('cancelled', 'Cancelled')], default='received', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customerprofile')),
                ('quotation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order', to='core.quotation')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='purchase_order',
            field=models.ForeignKey(blank=True, help_text='Customer PO this invoice is raised against', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='core.purchaseorder'),
        ),
    ]
