# Generated by Django 6.0.7 on 2026-07-27 17:17

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_purchaseorder_invoice_purchase_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amccontract',
            name='company',
            field=models.ForeignKey(default=core.models.get_default_company, on_delete=django.db.models.deletion.CASCADE, to='core.company'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='company',
            field=models.ForeignKey(default=core.models.get_default_company, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='core.company'),
        ),
        migrations.AlterField(
            model_name='division',
            name='company',
            field=models.ForeignKey(default=core.models.get_default_company, on_delete=django.db.models.deletion.CASCADE, to='core.company'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='company',
            field=models.ForeignKey(default=core.models.get_default_company, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='core.company'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='company',
            field=models.ForeignKey(default=core.models.get_default_company, on_delete=django.db.models.deletion.CASCADE, to='core.company'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='company',
            field=models.ForeignKey(default=core.models.get_default_company, on_delete=django.db.models.deletion.CASCADE, to='core.company'),
        ),
        migrations.AlterField(
            model_name='invoiceseries',
            name='company',
            field=models.ForeignKey(default=core.models.get_default_company, on_delete=django.db.models.deletion.CASCADE, to='core.company'),
        ),
        migrations.AlterField(
            model_name='product',
            name='company',
            field=models.ForeignKey(default=core.models.get_default_company, on_delete=django.db.models.deletion.CASCADE, to='core.company'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='company',
            field=models.ForeignKey(default=core.models.get_default_company, on_delete=django.db.models.deletion.CASCADE, to='core.company'),
        ),
        migrations.AlterField(
            model_name='productdocument',
            name='company',
            field=models.ForeignKey(default=core.models.get_default_company, on_delete=django.db.models.deletion.CASCADE, to='core.company'),
        ),
        migrations.AlterField(
            model_name='productsubcategory',
            name='company',
            field=models.ForeignKey(default=core.models.get_default_company, on_delete=django.db.models.deletion.CASCADE, to='core.company'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='company',
            field=models.ForeignKey(default=core.models.get_default_company, on_delete=django.db.models.deletion.CASCADE, to='core.company'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='company',
            field=models.ForeignKey(default=core.models.get_default_company, on_delete=django.db.models.deletion.CASCADE, to='core.company'),
        ),
        migrations.AlterField(
            model_name='serviceticket',
            name='company',
            field=models.ForeignKey(default=core.models.get_default_company, on_delete=django.db.models.deletion.CASCADE, to='core.company'),
        ),
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, default=core.models.get_default_company, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.company'),
        ),
    ]
