# Generated by Django 6.0.7 on 2026-07-27 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_salesorder_salesorderitem_salesorderseries_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoiceseries',
            options={'verbose_name': 'Invoice Series', 'verbose_name_plural': 'Invoice Series'},
        ),
    ]
