# Generated by Django 6.0.7 on 2026-07-30 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_invoiceseries_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='source',
            field=models.CharField(choices=[('email', 'Email'), ('repeat_order', 'Repeat Order'), ('oem_lead', 'OEM Lead'), ('direct_sales', 'Direct Sales'), ('tender', 'Tender'), ('showroom', 'Show Room'), ('online_platform', 'Online Platform'), ('architect_lead', 'Architect Lead'), ('other', 'Other')], default='email', max_length=20),
        ),
    ]
