# Generated by Django 6.0.7 on 2026-07-30 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_inquiry_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='sale_type',
            field=models.CharField(choices=[('direct', 'Direct Sales'), ('project', 'Project Sales')], default='direct', help_text='Direct Sales (retail/standard) or Project Sales (large/contracted projects)', max_length=10),
        ),
    ]
