# Generated by Django 6.0.7 on 2026-07-31 06:13

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_inquiry_sale_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Godown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('godown_type', models.CharField(choices=[('main', 'Main Godown'), ('sub', 'Sub Godown')], default='main', max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, help_text='Site / address of this godown', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(default=core.models.get_default_company, on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('parent_godown', models.ForeignKey(blank=True, help_text='For a Sub Godown, the Main Godown it receives stock from.', limit_choices_to={'godown_type': 'main'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_godowns', to='core.godown')),
            ],
            options={
                'verbose_name': 'Godown',
                'verbose_name_plural': 'Godowns',
                'ordering': ['godown_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('goods_high', 'Goods for Sale - High Side Goods'), ('goods_low', 'Goods for Sale - Low Side Goods'), ('tools_store', 'Tools - Store / Common Use'), ('tools_technician', 'Tools - Issued to Technician'), ('capital_employee', 'Capital Goods - Issued to Employee'), ('capital_common', 'Capital Goods - Common Use'), ('stationery', 'Stationery & Office Use Items'), ('spare_parts', 'Spare Parts'), ('returnable', 'Returnable Items'), ('scrap', 'Scrap')], max_length=20)),
                ('unit', models.CharField(choices=[('nos', 'Nos'), ('kg', 'Kg'), ('litre', 'Litre'), ('box', 'Box'), ('set', 'Set'), ('meter', 'Meter'), ('pair', 'Pair'), ('roll', 'Roll'), ('other', 'Other')], default='nos', max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('item_code', models.CharField(help_text='Internal store code for this item', max_length=100, unique=True)),
                ('reorder_level', models.PositiveIntegerField(default=0, help_text='Alert when total stock falls to/below this level')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(default=core.models.get_default_company, on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('linked_product', models.ForeignKey(blank=True, help_text="Link to the Sales catalog Product, if this is a sellable 'Goods for Sale' item", null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.product')),
            ],
            options={
                'verbose_name': 'Stock Item',
                'verbose_name_plural': 'Stock Items',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('transaction_type', models.CharField(choices=[('receipt', 'Stock Receipt (Inward / Purchase)'), ('transfer_in', 'Transfer In (from Main Godown)'), ('return', 'Returned to Store'), ('adjustment_in', 'Stock Adjustment - Increase'), ('transfer_out', 'Transfer Out (to Sub Godown)'), ('issue', 'Issued to Party'), ('scrap', 'Scrapped / Written Off'), ('adjustment_out', 'Stock Adjustment - Decrease')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('party_type', models.CharField(blank=True, choices=[('employee', 'Employee'), ('customer', 'Customer / Site'), ('other', 'Other / External Party')], max_length=10)),
                ('party_name', models.CharField(blank=True, help_text="Free-text party/site name (used when party type is 'Other', or as extra detail)", max_length=255)),
                ('transaction_date', models.DateField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True)),
                ('company', models.ForeignKey(default=core.models.get_default_company, on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('destination_godown', models.ForeignKey(blank=True, help_text="For 'Transfer Out': the Sub Godown receiving this stock", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_transfers', to='core.godown')),
                ('godown', models.ForeignKey(help_text='Godown this transaction is recorded against', on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='core.godown')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_transactions_handled', to='core.employee')),
                ('issued_to_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_issues', to='core.customerprofile')),
                ('issued_to_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_issues', to='core.employee')),
                ('related_transaction', models.ForeignKey(blank=True, help_text="For a 'Return' transaction: which Issue voucher this is returning against", limit_choices_to={'transaction_type': 'issue'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_transactions', to='core.stocktransaction')),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='core.stockitem')),
            ],
            options={
                'verbose_name': 'Stock Transaction',
                'verbose_name_plural': 'Stock Transactions',
                'ordering': ['-transaction_date', '-id'],
            },
        ),
    ]
