# Generated by Django 6.0.7 on 2026-07-31 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_godown_stockitem_stocktransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='sales_order',
            field=models.ForeignKey(blank=True, help_text='Project (Sales Order) this material was issued for / returned from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_transactions', to='core.salesorder'),
        ),
    ]
