# Generated by Django 6.0.7 on 2026-07-31 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_stocktransaction_sales_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='subcategory',
            field=models.CharField(blank=True, choices=[('high_side', 'High Side Goods'), ('low_side', 'Low Side Goods'), ('store_common', 'Store / Common Use'), ('technician', 'Issued to Technical Staff'), ('employee', 'Issued to Employee'), ('common_use', 'Common Use')], max_length=20),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='category',
            field=models.CharField(choices=[('goods_for_sale', 'Goods for Sale'), ('tools', 'Tools'), ('capital_goods', 'Capital Goods'), ('stationery', 'Stationery & Office Use Items'), ('spare_parts', 'Spare Parts'), ('returnable', 'Returnable Items'), ('scrap', 'Scrap')], max_length=20),
        ),
    ]
