# Generated by Django 6.0.7 on 2026-07-31 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_stockitem_subcategory_alter_stockitem_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockitem',
            name='subcategory',
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='category',
            field=models.CharField(choices=[('Goods for Sale', [('goods_high', 'High Side Goods'), ('goods_low', 'Low Side Goods')]), ('Tools', [('tools_store', 'Store / Common Use'), ('tools_technician', 'Issued to Technical Staff')]), ('Capital Goods', [('capital_employee', 'Issued to Employee'), ('capital_common', 'Common Use')]), ('stationery', 'Stationery & Office Use Items'), ('spare_parts', 'Spare Parts'), ('returnable', 'Returnable Items'), ('scrap', 'Scrap')], max_length=20),
        ),
    ]
