# Generated by Django 6.0.7 on 2026-07-31 07:35

import core.models
import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_stockitem_subcategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(default=core.models.get_default_company, on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
            options={
                'verbose_name': 'Stock Category',
                'verbose_name_plural': 'Stock Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_items', to='core.stockcategory'),
        ),
        migrations.CreateModel(
            name='StockSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='core.stockcategory')),
                ('company', models.ForeignKey(default=core.models.get_default_company, on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
            options={
                'verbose_name': 'Stock Sub-Category',
                'verbose_name_plural': 'Stock Sub-Categories',
                'ordering': ['category__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='stockitem',
            name='subcategory',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='category', chained_model_field='category', help_text='Only shown if the selected category has sub-categories', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_items', to='core.stocksubcategory'),
        ),
    ]
