# Generated by Django 6.0.7 on 2026-07-31 07:36

from django.db import migrations

CATEGORIES = [
    ('Goods for Sale', ['High Side Goods', 'Low Side Goods']),
    ('Tools', ['Store / Common Use', 'Issued to Technical Staff']),
    ('Capital Goods', ['Issued to Employee', 'Common Use']),
    ('Stationery & Office Use Items', []),
    ('Spare Parts', []),
    ('Returnable Items', []),
    ('Scrap', []),
]


def seed_categories(apps, schema_editor):
    Company = apps.get_model('core', 'Company')
    StockCategory = apps.get_model('core', 'StockCategory')
    StockSubCategory = apps.get_model('core', 'StockSubCategory')

    company = Company.objects.order_by('pk').first()
    if not company:
        return

    for category_name, subcategory_names in CATEGORIES:
        category, _ = StockCategory.objects.get_or_create(company=company, name=category_name)
        for sub_name in subcategory_names:
            StockSubCategory.objects.get_or_create(company=company, category=category, name=sub_name)


def remove_seeded_categories(apps, schema_editor):
    StockCategory = apps.get_model('core', 'StockCategory')
    StockCategory.objects.filter(name__in=[c for c, _ in CATEGORIES]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_stockcategory_alter_stockitem_category_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_categories, remove_seeded_categories),
    ]
