# Generated by Django 6.0.7 on 2026-07-31 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_project_purchaserequisition_purchaserequisitionitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequisitionitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('issued', 'Issued from Stock'), ('ordered', 'Purchase Ordered'), ('received', 'Received / Fulfilled')], default='pending', max_length=20),
        ),
    ]
