# Generated by Django 6.0.7 on 2026-07-31 14:42

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_purchaserequisitionitem_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('whatsapp_number', models.CharField(blank=True, help_text='Include country code, e.g. +919876543210', max_length=20)),
                ('address', models.TextField(blank=True)),
                ('gstin', models.CharField(blank=True, max_length=15, verbose_name='GSTIN')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(default=core.models.get_default_company, on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SupplierPurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent to Supplier'), ('confirmed', 'Confirmed by Supplier'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('company', models.ForeignKey(default=core.models.get_default_company, on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_purchase_orders', to='core.project')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='core.supplier')),
            ],
            options={
                'verbose_name': 'Purchase Order (Supplier)',
                'verbose_name_plural': 'Purchase Orders (Supplier)',
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='SupplierPurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, help_text='Auto-filled from the selected supplier quote for this line, if any', max_digits=12, null=True)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.supplierpurchaseorder')),
                ('requisition_item', models.ForeignKey(blank=True, help_text='Which Purchase Requisition line this fulfills, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='po_items', to='core.purchaserequisitionitem')),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.stockitem')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quoted_price', models.DecimalField(decimal_places=2, help_text='Price per unit', max_digits=12)),
                ('quoted_date', models.DateField(auto_now_add=True)),
                ('delivery_days', models.PositiveIntegerField(blank=True, help_text='Expected delivery time in days', null=True)),
                ('is_selected', models.BooleanField(default=False, help_text='Mark the chosen supplier for this item')),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('purchase_requisition_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_quotes', to='core.purchaserequisitionitem')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='core.supplier')),
            ],
            options={
                'verbose_name': 'Supplier Quote',
                'verbose_name_plural': 'Supplier Quotes',
                'ordering': ['quoted_price'],
            },
        ),
    ]
