# Generated by Django 6.0.7 on 2026-08-01 05:20

import core.models
import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_supplier_supplierpurchaseorder_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceticket',
            options={'ordering': ['-created_at'], 'verbose_name': 'Service Ticket', 'verbose_name_plural': 'Service Tickets'},
        ),
        migrations.RemoveField(
            model_name='serviceticket',
            name='assigned_engineer',
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='assigned_engineers',
            field=models.ManyToManyField(blank=True, help_text='Multiple technicians can be allocated to a single job', limit_choices_to={'user__role__name': 'Engineer'}, related_name='assigned_tickets', to='core.employee'),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='call_close_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='call_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='customer_remarks',
            field=models.TextField(blank=True, help_text='Remarks or feedback from the customer'),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='outcome',
            field=models.CharField(blank=True, choices=[('', 'Not Yet Attended'), ('completed', 'Completed'), ('pending', 'Pending')], max_length=20),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='pending_reason',
            field=models.CharField(blank=True, choices=[('other_complaint', 'Not Reached Due to Other Complaint Not Completed'), ('no_power', 'No Power at Site'), ('incomplete_safety', 'Due to Incomplete Safety Arrangement from Our Side'), ('parts_unavailable', 'Due to Parts Unavailability'), ('quotation_confirmation', 'Required to Give Quotation & Take Confirmation'), ('half_work_done', 'Due to Half Work Done')], max_length=30),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='problem_type',
            field=models.CharField(blank=True, choices=[('not_working', "Equipment Doesn't Work"), ('shows_error', 'Equipment Shows Error'), ('water_leakage', 'Water Leakage Problem'), ('no_cooling', 'Not Cooling Properly'), ('compressor_fail', 'Compressor Fail'), ('remote_problem', 'Remote Control Problem'), ('gas_leakage', 'Gas Leakage'), ('service_required', 'Service Required'), ('abnormal_sound', 'Equipment Sound Abnormal'), ('idu_not_working', 'IDU Not Working'), ('odu_not_working', 'ODU Not Working'), ('water_cooler_not_cooling', 'Water Not Cooling in Water Cooler'), ('deep_freezer_temp', 'Temperature Not Achieving in Deep Freezer'), ('ice_formation', 'Ice Formation'), ('improper_installation', 'Installation Not Properly Done'), ('other', 'Other')], max_length=30),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='received_via',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Phone Call'), ('when_visited', 'When Visited'), ('reach_another', 'When Reached for Another Problem'), ('oem', 'By OEM'), ('whatsapp', 'By WhatsApp')], default='phone', max_length=20),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='reported_by_mobile',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='reported_by_name',
            field=models.CharField(blank=True, help_text='Name of the person who reported the complaint (if different from the registered customer contact)', max_length=150),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='service_call_report',
            field=models.FileField(blank=True, help_text='Required before the ticket can be closed', null=True, upload_to='service_reports/'),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='ticket_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='serviceticket',
            name='resolution_notes',
            field=models.TextField(blank=True, help_text='Internal / technician remarks', null=True),
        ),
        migrations.AlterField(
            model_name='serviceticket',
            name='ticket_type',
            field=models.CharField(choices=[('warranty', 'Under Warranty'), ('amc', 'Under AMC'), ('chargeable', 'Chargeable Call'), ('foc', 'Free of Charge (FOC)'), ('installation', 'New Installation'), ('pm', 'Preventive Maintenance (AMC)')], default='chargeable', max_length=20, verbose_name='Complaint Type'),
        ),
        migrations.CreateModel(
            name='AMCCoverageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(default=core.models.get_default_company, on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
            options={
                'verbose_name': 'AMC Coverage Item',
                'verbose_name_plural': 'AMC Coverage Items',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_number', models.CharField(blank=True, max_length=50, unique=True, verbose_name='NOA Asset Number')),
                ('third_party_brand', models.CharField(blank=True, help_text='Fill if not a NOA-sold product', max_length=100)),
                ('model_number', models.CharField(blank=True, max_length=100)),
                ('serial_number', models.CharField(max_length=100)),
                ('model_description', models.TextField(blank=True)),
                ('installation_date', models.DateField(blank=True, null=True)),
                ('installation_site', models.CharField(blank=True, help_text='Site / location address (a customer can have equipment at multiple sites)', max_length=255)),
                ('warranty_start_date', models.DateField(blank=True, null=True)),
                ('warranty_end_date', models.DateField(blank=True, null=True)),
                ('amc_type', models.CharField(choices=[('none', 'No AMC'), ('comprehensive', 'Comprehensive (Parts & Labor)'), ('non_comprehensive', 'Non-Comprehensive (Labor Only)')], default='none', max_length=30)),
                ('amc_start_date', models.DateField(blank=True, null=True)),
                ('amc_end_date', models.DateField(blank=True, null=True)),
                ('services_per_period', models.PositiveIntegerField(default=0, help_text='No. of services covered under the AMC period')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amc_coverage_items', models.ManyToManyField(blank=True, help_text='What is covered under the AMC for this equipment', related_name='equipment', to='core.amccoverageitem')),
                ('category', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='division', chained_model_field='division', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.productcategory')),
                ('company', models.ForeignKey(default=core.models.get_default_company, on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='core.customerprofile')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.division')),
                ('product', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='subcategory', chained_model_field='subcategory', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.product')),
                ('subcategory', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='category', chained_model_field='category', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.productsubcategory')),
            ],
            options={
                'verbose_name': 'Equipment',
                'verbose_name_plural': 'Equipment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='equipment',
            field=models.ForeignKey(blank=True, help_text='The registered asset this complaint is against, if known', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='core.equipment'),
        ),
        migrations.CreateModel(
            name='EquipmentPartReplacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('replaced_under', models.CharField(choices=[('warranty', 'Under Warranty'), ('amc', 'Under AMC'), ('chargeable', 'Chargeable')], default='warranty', max_length=20)),
                ('replaced_date', models.DateField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_replacements', to='core.equipment')),
                ('service_ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='part_replacements', to='core.serviceticket')),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.stockitem')),
            ],
            options={
                'verbose_name': 'Part Replacement',
                'verbose_name_plural': 'Part Replacements',
                'ordering': ['-replaced_date'],
            },
        ),
        migrations.CreateModel(
            name='ServiceTicketPartUsed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.stockitem')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts_used', to='core.serviceticket')),
            ],
            options={
                'verbose_name': 'Part Used',
                'verbose_name_plural': 'Parts Used',
            },
        ),
    ]
