# Generated by Django 6.0.7 on 2026-08-01 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_remove_employee_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='alternate_contact_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='supplier',
            name='alternate_contact_person',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='supplier',
            name='bank_account_holder_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='supplier',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='supplier',
            name='bank_branch',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='supplier',
            name='bank_ifsc_code',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='supplier',
            name='bank_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='supplier',
            name='deals_in_items',
            field=models.ManyToManyField(blank=True, help_text='Items this supplier deals in - also used to search/filter suppliers by item.', related_name='suppliers', to='core.stockitem'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='pan_number',
            field=models.CharField(blank=True, max_length=10, verbose_name='PAN Number'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='payment_terms',
            field=models.CharField(blank=True, help_text='e.g. 50% advance, balance on delivery / Net 30', max_length=255),
        ),
        migrations.AddField(
            model_name='supplier',
            name='tan_number',
            field=models.CharField(blank=True, max_length=10, verbose_name='TAN Number'),
        ),
    ]
