# Generated by Django 6.0.7 on 2026-08-01 16:45

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_supplier_alternate_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='is_refillable',
            field=models.BooleanField(default=False, help_text='A reusable container that gets refilled rather than consumed (e.g. gas/refrigerant cylinder)'),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='is_returnable',
            field=models.BooleanField(default=False, help_text='Must come back to Store after being issued (e.g. Tools) - tracked on the Pending Returnable Items report'),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='is_serialized',
            field=models.BooleanField(default=False, help_text='Track individual serial numbers for this item (e.g. AC IDU/ODU, tools)'),
        ),
        migrations.CreateModel(
            name='StockItemSerial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('in_stock', 'In Stock'), ('issued', 'Issued'), ('scrapped', 'Scrapped')], default='in_stock', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('godown', models.ForeignKey(blank=True, help_text='Current / last known location', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_serials', to='core.godown')),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serials', to='core.stockitem')),
            ],
            options={
                'verbose_name': 'Stock Item Serial',
                'verbose_name_plural': 'Stock Item Serials',
                'ordering': ['stock_item__name', 'serial_number'],
                'unique_together': {('stock_item', 'serial_number')},
            },
        ),
        migrations.CreateModel(
            name='RefillLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_serial_number', models.CharField(blank=True, editable=False, max_length=100)),
                ('new_serial_number', models.CharField(blank=True, help_text='Leave blank if the serial number stays the same after refill', max_length=100)),
                ('refill_date', models.DateField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True)),
                ('company', models.ForeignKey(default=core.models.get_default_company, on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('godown', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refill_logs', to='core.godown')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refill_logs_handled', to='core.employee')),
                ('stock_item', models.ForeignKey(limit_choices_to={'is_refillable': True}, on_delete=django.db.models.deletion.PROTECT, related_name='refill_logs', to='core.stockitem')),
                ('serial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refill_logs', to='core.stockitemserial')),
            ],
            options={
                'verbose_name': 'Refill Entry',
                'verbose_name_plural': 'Refill Entries',
                'ordering': ['-refill_date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='serials',
            field=models.ManyToManyField(blank=True, help_text='For serialized items: the specific unit(s) this transaction covers', related_name='transactions', to='core.stockitemserial'),
        ),
    ]
