# Generated by Django 6.0.7 on 2026-08-01 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_stockitem_is_refillable_stockitem_is_returnable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='transaction_uom_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Quantity in the alternate unit above - Quantity (in the base Stock Unit) is calculated from this automatically.', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='unit',
            field=models.CharField(choices=[('nos', 'Nos'), ('kg', 'Kg'), ('litre', 'Litre'), ('box', 'Box'), ('set', 'Set'), ('meter', 'Meter'), ('pair', 'Pair'), ('roll', 'Roll'), ('other', 'Other')], default='nos', help_text='Base Stock Unit - stock balance is always maintained in this unit. Add Alternate UOMs below for items purchased/issued in a different unit (e.g. bought by weight, issued by count or length).', max_length=10),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='quantity',
            field=models.DecimalField(decimal_places=2, help_text="In the item's base Stock Unit. Auto-calculated if an alternate unit is used below.", max_digits=12),
        ),
        migrations.CreateModel(
            name='StockItemUOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(choices=[('nos', 'Nos'), ('kg', 'Kg'), ('litre', 'Litre'), ('box', 'Box'), ('set', 'Set'), ('meter', 'Meter'), ('pair', 'Pair'), ('roll', 'Roll'), ('other', 'Other')], max_length=10)),
                ('conversion_factor', models.DecimalField(decimal_places=6, help_text="How many of the item's base Stock Unit make up 1 of this unit. E.g. base unit is KG, this unit is Nos, each piece weighs 0.05 KG -> enter 0.05 (1 Nos = 0.05 KG).", max_digits=14)),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternate_uoms', to='core.stockitem')),
            ],
            options={
                'verbose_name': 'Alternate UOM',
                'verbose_name_plural': 'Alternate UOMs',
                'ordering': ['stock_item__name', 'unit'],
                'unique_together': {('stock_item', 'unit')},
            },
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='transaction_uom',
            field=models.ForeignKey(blank=True, help_text="Enter this transaction in a different unit than the item's base Stock Unit (e.g. purchase by weight but issue by count or length).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='core.stockitemuom'),
        ),
    ]
