# Generated by Django 6.0.7 on 2026-08-01 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_stocktransaction_transaction_uom_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='unit',
            field=models.CharField(choices=[('nos', 'Nos'), ('kg', 'Kg'), ('litre', 'Litre'), ('box', 'Box'), ('set', 'Set'), ('meter', 'Mtr'), ('ft', 'Ft'), ('rft', 'RFT'), ('sqft', 'Sq. Ft'), ('pair', 'Pair'), ('roll', 'Roll'), ('other', 'Other')], default='nos', help_text='Base Stock Unit - stock balance is always maintained in this unit. Add Alternate UOMs below for items purchased/issued in a different unit (e.g. bought by weight, issued by count or length).', max_length=10),
        ),
        migrations.AlterField(
            model_name='stockitemuom',
            name='unit',
            field=models.CharField(choices=[('nos', 'Nos'), ('kg', 'Kg'), ('litre', 'Litre'), ('box', 'Box'), ('set', 'Set'), ('meter', 'Mtr'), ('ft', 'Ft'), ('rft', 'RFT'), ('sqft', 'Sq. Ft'), ('pair', 'Pair'), ('roll', 'Roll'), ('other', 'Other')], max_length=10),
        ),
    ]
