# Generated by Django 6.0.7 on 2026-08-01 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_stockitem_unit_alter_stockitemuom_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='expected_issue_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Reference only: the equivalent quantity in the Expected Issue Unit above.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='expected_issue_uom',
            field=models.ForeignKey(blank=True, help_text='Reference only: which unit this stock is expected to be issued in later (e.g. received by weight, planned to be issued by length). Does not affect the stock ledger.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.stockitemuom'),
        ),
    ]
