# Generated by Django 6.0.7 on 2026-08-01 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_stocktransaction_expected_issue_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='is_piece_tracked',
            field=models.BooleanField(default=False, help_text='Total stock is made up of individual pieces of different sizes (e.g. Copper Pipe: several cut lengths adding up to the total Ft in stock) - track and select by piece instead of a single bulk quantity'),
        ),
        migrations.CreateModel(
            name='StockItemPiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text="Optional reference tag (e.g. 'Roll A'). Auto-numbered if left blank.", max_length=50)),
                ('quantity', models.DecimalField(decimal_places=2, help_text="Size of this piece, in the item's base Stock Unit", max_digits=12)),
                ('status', models.CharField(choices=[('in_stock', 'In Stock'), ('issued', 'Issued'), ('scrapped', 'Scrapped')], default='in_stock', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('godown', models.ForeignKey(blank=True, help_text='Current / last known location', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_pieces', to='core.godown')),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='core.stockitem')),
            ],
            options={
                'verbose_name': 'Stock Item Piece',
                'verbose_name_plural': 'Stock Item Pieces',
                'ordering': ['stock_item__name', '-quantity'],
            },
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='pieces',
            field=models.ManyToManyField(blank=True, help_text='For piece-tracked items: the specific piece(s) this transaction covers', related_name='transactions', to='core.stockitempiece'),
        ),
    ]
