# Generated by Django 6.0.7 on 2026-08-01 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_stockitem_is_piece_tracked_stockitempiece_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransaction',
            name='expected_issue_uom',
            field=models.CharField(blank=True, choices=[('nos', 'Nos'), ('kg', 'Kg'), ('litre', 'Litre'), ('box', 'Box'), ('set', 'Set'), ('meter', 'Mtr'), ('ft', 'Ft'), ('rft', 'RFT'), ('sqft', 'Sq. Ft'), ('pair', 'Pair'), ('roll', 'Roll'), ('other', 'Other')], help_text='Which unit this stock is tracked/issued in (should match Quantity below).', max_length=10),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='transaction_uom',
            field=models.CharField(blank=True, choices=[('nos', 'Nos'), ('kg', 'Kg'), ('litre', 'Litre'), ('box', 'Box'), ('set', 'Set'), ('meter', 'Mtr'), ('ft', 'Ft'), ('rft', 'RFT'), ('sqft', 'Sq. Ft'), ('pair', 'Pair'), ('roll', 'Roll'), ('other', 'Other')], help_text='Reference only: also express this transaction in a different unit (e.g. what was purchased in).', max_length=10),
        ),
        migrations.RemoveField(
            model_name='stocktransaction',
            name='expected_issue_quantity',
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='quantity',
            field=models.DecimalField(decimal_places=2, help_text="In the item's base Stock Unit - the authoritative amount the stock ledger runs on.", max_digits=12),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='transaction_uom_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Reference only: quantity in the unit above. Does not affect Quantity below.', max_digits=12, null=True),
        ),
        migrations.DeleteModel(
            name='StockItemUOM',
        ),
    ]
