# Generated by Django 6.0.7 on 2026-08-02 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_stocktransaction_expected_issue_uom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='preferred_printer',
            field=models.CharField(blank=True, help_text="Reference note only (e.g. 'HP LaserJet - Front Desk'). Browsers don't allow a webpage to silently pick a printer - when this user clicks Print, their browser's own print dialog opens and they choose the printer there.", max_length=150),
        ),
        migrations.AddField(
            model_name='employee',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text="This user's own WhatsApp number, include country code e.g. +919876543210. Used to identify/contact this user from within the CRM (WhatsApp itself always sends from whichever device/account is logged in).", max_length=20),
        ),
    ]
