# Generated by Django 6.0.7 on 2026-08-02 10:11

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_department_permission_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('letter_date', models.DateField(auto_now_add=True)),
                ('candidate_title', models.CharField(choices=[('Mr.', 'Mr.'), ('Ms.', 'Ms.'), ('Mrs.', 'Mrs.')], default='Mr.', max_length=5)),
                ('candidate_name', models.CharField(help_text='Full name, e.g. Aaditya Solanki', max_length=200)),
                ('candidate_address', models.TextField(blank=True)),
                ('designation', models.CharField(help_text='e.g. Trainee Project Engineer', max_length=100)),
                ('department', models.CharField(help_text='e.g. Project Department', max_length=100)),
                ('expected_joining_date', models.DateField(help_text='You have to join on or before this date')),
                ('monthly_remuneration', models.DecimalField(decimal_places=2, help_text='Monthly salary in Rs. - the amount in words is generated automatically', max_digits=10)),
                ('conveyance_allowance', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Fixed monthly petrol/conveyance reimbursement, if any', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(default=core.models.get_default_company, on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('employee', models.ForeignKey(blank=True, help_text='Link to their Employee record, once created (e.g. after they actually join)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offer_letters', to='core.employee')),
            ],
            options={
                'verbose_name': 'Offer Letter',
                'verbose_name_plural': 'Offer Letters',
                'ordering': ['-created_at'],
            },
        ),
    ]
