# Generated by Django 6.0.7 on 2026-08-02 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_offerletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerletter',
            name='candidate_email',
            field=models.EmailField(blank=True, help_text='Used to pre-fill the Email form for this letter', max_length=254),
        ),
        migrations.AddField(
            model_name='offerletter',
            name='candidate_phone',
            field=models.CharField(blank=True, help_text='With country code if possible, e.g. 919227711980 - used for the WhatsApp share link', max_length=20),
        ),
        migrations.AddField(
            model_name='offerletter',
            name='interview_date',
            field=models.DateField(blank=True, help_text='Date the candidate was interviewed', null=True),
        ),
        migrations.AddField(
            model_name='offerletter',
            name='interview_remarks',
            field=models.TextField(blank=True, help_text='Notes/evaluation from the interview - internal use only, not printed on the letter'),
        ),
        migrations.AddField(
            model_name='offerletter',
            name='interviewed_by',
            field=models.ForeignKey(blank=True, help_text='Employee who conducted the interview', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interviews_conducted', to='core.employee'),
        ),
    ]
