# Generated by Django 6.0.7 on 2026-08-02 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_offerletter_candidate_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offerletter',
            name='conveyance_allowance',
        ),
        migrations.AddField(
            model_name='offerletter',
            name='esic_applicable',
            field=models.BooleanField(default=False, help_text='Tick to include ESIC for this offer (statutory if gross wage is Rs 21,000 or below)'),
        ),
        migrations.AddField(
            model_name='offerletter',
            name='esic_employee_contribution',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank to auto-calculate at 0.75% of monthly remuneration, or enter your own amount', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='offerletter',
            name='esic_employer_contribution',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank to auto-calculate at 3.25% of monthly remuneration, or enter your own amount', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='offerletter',
            name='pf_applicable',
            field=models.BooleanField(default=False, help_text='Tick to include Provident Fund for this offer'),
        ),
        migrations.AddField(
            model_name='offerletter',
            name='pf_employee_contribution',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank to auto-calculate at 12% of monthly remuneration, or enter your own amount', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='offerletter',
            name='pf_employer_contribution',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank to auto-calculate at 12% of monthly remuneration, or enter your own amount', max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='OfferLetterAllowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Conveyance Allowance, HRA, Special Allowance', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Monthly amount in Rs.', max_digits=10)),
                ('offer_letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowances', to='core.offerletter')),
            ],
            options={
                'verbose_name': 'Allowance',
                'verbose_name_plural': 'Allowances',
            },
        ),
        migrations.CreateModel(
            name='OfferLetterFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Mobile Reimbursement, Medical Insurance', max_length=150)),
                ('description', models.CharField(blank=True, help_text='Optional extra detail shown on the letter', max_length=255)),
                ('offer_letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='core.offerletter')),
            ],
            options={
                'verbose_name': 'Other Facility',
                'verbose_name_plural': 'Other Facilities',
            },
        ),
    ]
