# Generated by Django 6.0.7 on 2026-08-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_remove_offerletter_conveyance_allowance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerletter',
            name='conveyance_allowance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Fixed monthly petrol/conveyance reimbursement, if any', max_digits=10),
        ),
    ]
