# Generated by Django 6.0.7 on 2026-08-02 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_rename_service_hub_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='amccontract',
            name='coverage_items',
            field=models.ManyToManyField(blank=True, help_text='What is covered under this AMC contract', related_name='amc_contracts', to='core.amccoverageitem'),
        ),
    ]
