# Generated by Django 6.0.7 on 2026-08-03 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_amccontract_coverage_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widgets', models.JSONField(blank=True, default=list, help_text='Ordered list of dashboard card keys. Empty means use the role preset.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dashboard Preference',
                'verbose_name_plural': 'Dashboard Preferences',
            },
        ),
    ]
