# Generated by Django 6.0.7 on 2026-07-31 14:26

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0024_purchaserequisitionitem_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemsToPurchase',
            fields=[
            ],
            options={
                'verbose_name': 'Item to Purchase',
                'verbose_name_plural': 'Items to Purchase',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.purchaserequisitionitem',),
        ),
    ]
