# Generated by Django 6.0.7 on 2026-07-31 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_supplier_supplierpurchaseorder_and_more'),
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierPurchaseOrder',
            fields=[
            ],
            options={
                'verbose_name': 'Purchase Order',
                'verbose_name_plural': 'Purchase Orders',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.supplierpurchaseorder',),
        ),
    ]
