# Generated by Django 6.0.7 on 2026-08-01 11:28

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0027_remove_employee_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HREmployee',
            fields=[
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employee Master',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.employee',),
        ),
    ]
