# Generated by Django 6.0.7 on 2026-08-04 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_dashboard_preference'),
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HROfferLetter',
            fields=[
            ],
            options={
                'verbose_name': 'Offer Letter',
                'verbose_name_plural': 'Offer Letters',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.offerletter',),
        ),
    ]
