# Generated by Django 6.0.1 on 2026-06-28 16:11

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_remove_inquiry_products_amccontract_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAMCContract',
            fields=[
            ],
            options={
                'verbose_name': 'AMCContract',
                'verbose_name_plural': 'AMC Contracts',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.amccontract',),
        ),
        migrations.CreateModel(
            name='ServiceServiceTicket',
            fields=[
            ],
            options={
                'verbose_name': 'ServiceTicket',
                'verbose_name_plural': 'Service Tickets',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.serviceticket',),
        ),
    ]
