# Generated by Django 6.0.7 on 2026-08-01 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_serviceticket_options_and_more'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceEquipment',
            fields=[
            ],
            options={
                'verbose_name': 'Equipment',
                'verbose_name_plural': 'Equipment',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.equipment',),
        ),
    ]
