# Generated by Django 6.0.7 on 2026-08-01 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_serviceticket_options_and_more'),
        ('service', '0002_serviceequipment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingComplaints',
            fields=[
            ],
            options={
                'verbose_name': 'Pending Complaint',
                'verbose_name_plural': 'Pending Complaints',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.serviceticket',),
        ),
    ]
