# Generated by Django 6.0.7 on 2026-08-01 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_remove_employee_address_and_more'),
        ('service', '0003_pendingcomplaints'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAMCCoverageItem',
            fields=[
            ],
            options={
                'verbose_name': 'AMC Coverage Item',
                'verbose_name_plural': 'AMC Coverage Items',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.amccoverageitem',),
        ),
    ]
