# Generated by Django 6.0.1 on 2026-06-28 16:11

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_remove_inquiry_products_amccontract_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryProduct',
            fields=[
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.product',),
        ),
        migrations.CreateModel(
            name='InventoryProductCategory',
            fields=[
            ],
            options={
                'verbose_name': 'ProductCategory',
                'verbose_name_plural': 'Product Categories',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.productcategory',),
        ),
        migrations.CreateModel(
            name='InventoryProductDocument',
            fields=[
            ],
            options={
                'verbose_name': 'ProductDocument',
                'verbose_name_plural': 'Product Documents',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.productdocument',),
        ),
        migrations.CreateModel(
            name='InventoryProductSubCategory',
            fields=[
            ],
            options={
                'verbose_name': 'Product Sub-Category',
                'verbose_name_plural': 'Product Sub-Categories',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.productsubcategory',),
        ),
    ]
