# Generated by Django 6.0.1 on 2026-06-28 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_division_options_product_model_number'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryDivision',
            fields=[
            ],
            options={
                'verbose_name': 'Division',
                'verbose_name_plural': 'Divisions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.division',),
        ),
        migrations.AlterModelOptions(
            name='inventoryproductcategory',
            options={'verbose_name': 'Product Category', 'verbose_name_plural': 'Product Categories'},
        ),
        migrations.AlterModelOptions(
            name='inventoryproductdocument',
            options={'verbose_name': 'Product Document', 'verbose_name_plural': 'Product Documents'},
        ),
    ]
