# Generated by Django 6.0.7 on 2026-07-31 14:00

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0023_project_purchaserequisition_purchaserequisitionitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.project',),
        ),
        migrations.CreateModel(
            name='PurchaseRequisition',
            fields=[
            ],
            options={
                'verbose_name': 'Purchase Requisition',
                'verbose_name_plural': 'Purchase Requisitions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.purchaserequisition',),
        ),
    ]
