# Generated by Django 6.0.1 on 2026-06-28 16:11

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_remove_inquiry_products_amccontract_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesCustomerProfile',
            fields=[
            ],
            options={
                'verbose_name': 'CustomerProfile',
                'verbose_name_plural': 'Customer Profiles',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.customerprofile',),
        ),
        migrations.CreateModel(
            name='SalesInquiry',
            fields=[
            ],
            options={
                'verbose_name': 'Inquiry',
                'verbose_name_plural': 'Inquiries',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.inquiry',),
        ),
        migrations.CreateModel(
            name='SalesInvoice',
            fields=[
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.invoice',),
        ),
        migrations.CreateModel(
            name='SalesQuotation',
            fields=[
            ],
            options={
                'verbose_name': 'Quotation',
                'verbose_name_plural': 'Quotations',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.quotation',),
        ),
    ]
