# Generated by Django 6.0.7 on 2026-08-01 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_remove_employee_address_and_more'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesInvoiceSeries',
            fields=[
            ],
            options={
                'verbose_name': 'Invoice Series',
                'verbose_name_plural': 'Invoice Series',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.invoiceseries',),
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
            ],
            options={
                'verbose_name': 'Sales Order',
                'verbose_name_plural': 'Sales Orders',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.salesorder',),
        ),
        migrations.CreateModel(
            name='SalesOrderSeries',
            fields=[
            ],
            options={
                'verbose_name': 'Sales Order Series',
                'verbose_name_plural': 'Sales Order Series',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.salesorderseries',),
        ),
        migrations.CreateModel(
            name='SalesPurchaseOrder',
            fields=[
            ],
            options={
                'verbose_name': 'Purchase Order',
                'verbose_name_plural': 'Purchase Orders',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.purchaseorder',),
        ),
    ]
